name: Simple 1Password SSH Example

# This workflow demonstrates the minimal setup needed to use SSH keys from 1Password

on:
  workflow_dispatch:

jobs:
  ssh-example:
    runs-on: ubuntu-latest

    environment:
      name: testenv

    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Setup SSH from 1Password
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          # Sign in to 1Password using the service account ans read a test "secret"
          op read "op://WebDevTest/SSH Key/supersecret"
