name: Deploy with 1Password SSH Key

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install 1Password CLI
              uses: 1password/install-cli-action@v1

            - name: Load SSH key from 1Password
              env:
                  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
              run: |
                  # Create SSH directory
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh

                  # Retrieve SSH private key from 1Password
                  # Replace 'SSH_KEY_ITEM_ID' with your actual 1Password item ID or reference
                  op read "op://Private/SSH_KEY_ITEM_ID/private key" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

                  # Optionally retrieve SSH public key
                  op read "op://Private/SSH_KEY_ITEM_ID/public key" > ~/.ssh/id_rsa.pub
                  chmod 644 ~/.ssh/id_rsa.pub

                  # Add known hosts (replace with your actual host)
                  ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

            - name: Test SSH connection
              run: |
                  # Test the SSH connection (replace with your actual host/user)
                  ssh -o StrictHostKeyChecking=no user@your-server.com "echo 'SSH connection successful'"

            - name: Deploy application
              run: |
                  # Your deployment commands here
                  echo "Deploying application..."
                  # Example: rsync, scp, or direct SSH commands
                  # ssh user@your-server.com "cd /path/to/app && git pull && restart-service"
